{
  "project": {
    "name": "BookingManagementSystem",
    "files": {
      "index.php": "<?php\nrequire 'database.php';\n\n// Endpoint per la prenotazione\nif ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'book') {\n    $date = $_POST['date'];\n    $time = $_POST['time'];\n    $employee_id = $_POST['employee_id'];\n    bookAppointment($date, $time, $employee_id);\n}\n\n// Endpoint per la gestione dei dipendenti\nif ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'manage_employee') {\n    $employee_id = $_POST['employee_id'];\n    $action = $_POST['action_type'];\n    manageEmployee($employee_id, $action);\n}\n\nfunction bookAppointment($date, $time, $employee_id) {\n    $db = new Database();\n    $db->query('INSERT INTO bookings (date, time, employee_id) VALUES (:date, :time, :employee_id)');\n    $db->bind(':date', $date);\n    $db->bind(':time', $time);\n    $db->bind(':employee_id', $employee_id);\n    $db->execute();\n}\n\nfunction manageEmployee($employee_id, $action) {\n    $db = new Database();\n    if ($action === 'add') {\n        $db->query('INSERT INTO employees (id) VALUES (:employee_id)');\n        $db->bind(':employee_id', $employee_id);\n    } elseif ($action === 'remove') {\n        $db->query('DELETE FROM employees WHERE id = :employee_id');\n        $db->bind(':employee_id', $employee_id);\n    }\n    $db->execute();\n}\n?>",
      "database.php": "<?php\nclass Database {\n    private $host = 'localhost';\n    private $db_name = 'booking_system';\n    private $username = 'root';\n    private $password = '';\n    private $conn;\n\n    public function __construct() {\n        $this->connect();\n    }\n\n    public function connect() {\n        $this->conn = null;\n        try {\n            $this->conn = new PDO('mysql:host=' . $this->host . ';dbname=' . $this->db_name, $this->username, $this->password);\n            $this->conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n        } catch (PDOException $exception) {\n            echo 'Connection error: ' . $exception->getMessage();\n        }\n        return $this->conn;\n    }\n\n    public function query($sql) {\n        $this->stmt = $this->conn->prepare($sql);\n    }\n\n    public function bind($param, $value, $type = null) {\n        if (is_null($type)) {\n            switch (true) {\n                case is_int($value):\n                    $type = PDO::PARAM_INT;\n                    break;\n                case is_bool($value):\n                    $type = PDO::PARAM_BOOL;\n                    break;\n                case is_null($value):\n                    $type = PDO::PARAM_NULL;\n                    break;\n                default:\n                    $type = PDO::PARAM_STR;\n            }\n        }\n        $this->stmt->bindValue($param, $value, $type);\n    }\n\n    public function execute() {\n        return $this->stmt->execute();\n    }\n}\n?>",
      "create_tables.sql": "-- SQL per creare le tabelle necessarie\nCREATE TABLE IF NOT EXISTS employees (\n    id INT PRIMARY KEY\n);\n\nCREATE TABLE IF NOT EXISTS bookings (\n    id INT AUTO_INCREMENT PRIMARY KEY,\n    date DATE NOT NULL,\n    time TIME NOT NULL,\n    employee_id INT,\n    FOREIGN KEY (employee_id) REFERENCES employees(id)\n);"
    }
  }
}